# What is Pandas?
Pandas is a Python library used for data manipulation, data processing, and data analysis.
The name Pandas comes from "Panel Data", which refers to structured data arranged in rows and columns.
Pandas is mainly used to work with structured/tabular data.

# What kind of data can Pandas handle?
Pandas can work with data from various sources, such as:

CSV files
Excel files
JSON files
SQL databases

# How is Pandas used?
1. Data Processing

Cleaning data
Handling missing values
Removing duplicates
Handling incorrect data
Encoding categorical data
Transforming data

2. Data Analytics

Querying and filtering data
Sorting data
Grouping and aggregating data
Finding meaningful patterns and insights

# Why is Pandas popular?
It can efficiently work with large datasets, including datasets with 100,000+ rows.
It provides easy-to-use functions for manipulating and analyzing data.
It integrates well with other Python libraries such as NumPy, Matplotlib, and Seaborn.

Pandas = A Python tool used to load, clean, manipulate, analyze, and understand structured data.

In [3]:
import pandas as pd

name=pd.Series(['Netra','Panchal','BBA'])
print(name,type(name))

0      Netra
1    Panchal
2        BBA
dtype: str <class 'pandas.Series'>

In [7]:
name.size

3

In [8]:
name.shape

(3,)

In [9]:
name.ndim

1

In [10]:
name.index

RangeIndex(start=0, stop=3, step=1)

In [12]:
name.values

<StringArray>
['Netra', 'Panchal', 'BBA']
Length: 3, dtype: str

In [11]:
len(name)

3

In [13]:
df = pd.DataFrame({
    "a": [100,200,300],
    "b": [400,500,600],
    "c": [700,800,900],
    "d": [1000,1100,1200]

})
df

     a    b    c     d
0  100  400  700  1000
1  200  500  800  1100
2  300  600  900  1200

Pandas has 2 types of Indexes
1 Implicit Index ==> Python Internal Indexes
  - df [Start : Stop : Step]
  - [stop - excluded, start default - 0,    Step default - 1 ]
2 Explicit Index ==> Labelled Indexes
  - - df [Start : Stop : Step]
  - [stop - included, start default -start value of lablled index, Step default - 1 ]

  - df.loc() [Location means Index]

In [15]:

df.iloc[1]

a     200
b     500
c     800
d    1100
Name: 1, dtype: int64

In [ ]:
df.iloc[0:2:1]

In [ ]:
#issue
df.index = [1,2,3]
df

     a    b    c     d
1  100  400  700  1000
2  200  500  800  1100
3  300  600  900  1200

In [17]:
df.iloc[1]

a     200
b     500
c     800
d    1100
Name: 2, dtype: int64

In [1]:
df.loc["a"]

NameError: name 'df' is not defined

In [ ]:
df.loc[0 ::2]

     a    b    c     d
1  100  400  700  1000
3  300  600  900  1200

In [20]:
df.iloc[0 ::2]

     a    b    c     d
1  100  400  700  1000
3  300  600  900  1200

In [1]:
import seaborn as sns

data_titanic = sns.load_dataset('titanic')

Matplotlib is building the font cache; this may take a moment.

In [4]:
df = pd.DataFrame(data_titanic)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

For Access data From .CSV file
df1 = pd.read_csv("PATH")
df1

replace all \ with //
replace all with \ with /
use r (r means row string)

In [5]:
df.shape

(891, 15)

In [6]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [7]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [8]:
df.size

13365

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [10]:
df.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

In [ ]:
#Stastics of Numerical Data
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
#Stastics of Categorical Data
df.describe(include='object')

C:\Users\DELL\AppData\Local\Temp\ipykernel_13700\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

         sex embarked  who  embark_town alive
count    891      889  891          889   891
unique     2        3    3            3     2
top     male        S  man  Southampton    no
freq     577      644  537          644   549

Stastics of Categorical and Numerical Data

In [14]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
survived,891.0,NaN,NaN,NaN,0.383838,0.486592,0.0,0.0,0.0,1.0,1.0
pclass,891.0,NaN,NaN,NaN,2.308642,0.836071,1.0,2.0,3.0,3.0,3.0
sex,891,2,male,577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,714.0,NaN,NaN,NaN,29.699118,14.526497,0.42,20.125,28.0,38.0,80.0
sibsp,891.0,NaN,NaN,NaN,0.523008,1.102743,0.0,0.0,0.0,1.0,8.0
parch,891.0,NaN,NaN,NaN,0.381594,0.806057,0.0,0.0,0.0,0.0,6.0
fare,891.0,NaN,NaN,NaN,32.204208,49.693429,0.0,7.9104,14.4542,31.0,512.3292
embarked,889,3,S,644,NaN,NaN,NaN,NaN,NaN,NaN,NaN
class,891,3,Third,491,NaN,NaN,NaN,NaN,NaN,NaN,NaN
who,891,3,man,537,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adult_male,891,2,True,537,NaN,NaN,NaN,NaN,NaN,NaN,NaN
deck,203,7,C,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
embark_town,889,3,Southampton,644,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alive,891,2,no,549,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alone,891,2,True,537,NaN,NaN,NaN,NaN,NaN,NaN,NaN